### PR TITLE
feat(api-core): add beacon support to log messages

### LINKED ISSUE #60: Investigate navigator.sendBeacon() for analytics
- https://www.smashingmagazine.com/2018/07/logging-activity-web-beacon-api
- IE 11 would be issue https://github.com/miguelmota/Navigator.sendBeacon

### PR DESCRIPTION
**Pull request by nylon22**
Opening as draft as there are accompanying backend changes for this PR that have not been released

closes #60

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
You may want to validate / verify that navigator.beacon (which is a POST) will work with the `SameSite=lax` on the cookie (which prevents POSTs that are not directly from the same domain), or you will not be able to tell who the user is or that the person is authenticated at all. The latter may come more into play if the log endpoint requires authentication.

**Comment by robmcguinness** [comment]
Some notes: https://w3c.github.io/beacon/#privacy-and-security

**Comment by TheSharpieOne** [comment]
The spec doesn't mention the `SameSite` flag on sending cookies. If you recall, the `SameSite` flag was in use at Availity before it was implemented by the browsers. When Chrome finally supported it, it broke all of the outbound SSO since those links were using blankshield which opened a new blank iframe before directing. Because that iframe was not availity.com, it did not send the cookie and the request was not authenticated. Similar, the User Agent making the request is not availity.com so the cookie will not be set.
From the looks of Chromium's code, it's not going to send the cookie if it has `SameSite=lax` on a beacon POST. If that is the case, it may just be an oversight or a bug within chromium. Also, `SameSite=lax` may soon be the default; requiring `SameSite=none` to be specified.

**Comment by nylon22** [comment]
@TheSharpieOne Thank you for all of the feedback. We were able get the request to work with a canary release of this PR.

I'm still going to leave this PR as a draft until the business approves releasing it.

**Pull request merged**
